In [4]:
import pandas as pd
import glob

In [5]:
files = glob.glob("data/*.parquet")

In [6]:
dfs = []

for f in files:
    df = pd.read_parquet(f)
    dfs.append(df)

df_all = pd.concat(dfs, ignore_index=True)

print("Total rows:", len(df_all))

Total rows: 75750

In [7]:
df_all.shape

(75750, 15)

In [8]:
df_all

,image,label,id,clip_tags_ViT_L_14_with_openai_classes,clip_tags_ViT_L_14_wo_openai_classes,clip_tags_ViT_L_14_simple_specific,clip_tags_ViT_L_14_ensemble_specific,clip_tags_ViT_B_16_simple_specific,clip_tags_ViT_B_16_ensemble_specific,clip_tags_ViT_B_32_simple_specific,clip_tags_ViT_B_32_ensemble_specific,Attributes_ViT_L_14_descriptors_text_davinci_003_full,Attributes_LAION_ViT_H_14_2B_descriptors_text_davinci_003_full,clip_tags_LAION_ViT_H_14_2B_simple_specific,clip_tags_LAION_ViT_H_14_2B_ensemble_specific
0,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,6,0,"[deep fried mars bar, beignets, fried dough, f...","[beignets, fork, dessert, pancakes, bread pudd...",beignets,beignets,beignets,beignets,beignets,beignets,"[beignet which has square or round in shape, b...","[beignet which has square or round in shape, b...",beignets,beignets
1,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,6,1,"[beignets, sugar bowl, fried food, fried dough...","[beignets, beignet]",beignets,beignets,beignets,beignets,beignets,beignets,"[beignets which has served warm, beignets whic...","[beignets which has served warm, beignets whic...",beignets,beignets
2,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,6,2,"[beignets, sugar bowl, cajun food, mardi gras,...","[beignets, eater, beignet, mobile]",beignets,beignets,beignets,beignets,beignets,beignets,"[beignets which has round or square shape, bei...","[beignet which has golden-brown in color, beig...",beignets,beignets
3,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,6,3,"[crab cakes, brandade, falafel, fried clams, c...","[crab cakes, falafel, beignets, appetizer, eater]",crab cakes,crab cakes,crab cakes,crab cakes,falafel,falafel,[fritter which may be served with a dipping sa...,"[falafel which has small, round, deep-fried ba...",falafel,falafel
4,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,6,4,"[beignets, fried dough, zeppole, loukoumades, ...","[beignets, beignet, cruller, bolotie, fritter]",beignets,beignets,beignets,beignets,beignets,beignets,"[beignet which has square or round in shape, b...","[beignet which has golden-brown in color, beig...",beignets,beignets
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75745,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,90,75745,"[amatriciana sauce, spaghetti bolognese, bolog...","[spaghetti bolognese, spaghetti carbonara, car...",spaghetti bolognese,spaghetti bolognese,spaghetti bolognese,spaghetti bolognese,spaghetti bolognese,spaghetti bolognese,[spaghetti bolognese which has plate of spaghe...,"[spaghetti bolognese which has onions, spaghet...",spaghetti bolognese,spaghetti bolognese
75746,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,90,75746,"[spaghetti bolognese, bolognese, bolognese sau...","[spaghetti bolognese, spaghetti carbonara, eat...",spaghetti bolognese,spaghetti bolognese,spaghetti bolognese,spaghetti bolognese,spaghetti bolognese,spaghetti bolognese,"[spaghetti bolognese which has ground beef, sp...",[spaghetti bolognese which has plate of spaghe...,spaghetti bolognese,spaghetti bolognese
75747,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,90,75747,"[spaghetti bolognese, spaghetti alla puttanesc...","[spaghetti bolognese, spaghetti carbonara, mea...",spaghetti bolognese,spaghetti bolognese,spaghetti bolognese,spaghetti bolognese,spaghetti bolognese,spaghetti bolognese,[spaghetti bolognese which has plate of spaghe...,"[spaghetti bolognese which has garlic, spaghet...",spaghetti bolognese,spaghetti bolognese
75748,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,90,75748,"[spaghetti alla puttanesca, fra diavolo sauce,...","[spaghetti bolognese, spaghetti carbonara, mea...",spaghetti bolognese,spaghetti bolognese,spaghetti bolognese,spaghetti bolognese,spaghetti bolognese,spaghetti bolognese,[spaghetti bolognese which has plate of spaghe...,"[meatball which has small to medium in size, m...",spaghetti bolognese,spaghetti bolognese
75749,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,90,75749,"[spaghetti bolognese, bolognese sauce, bologne...","[spaghetti bolognese, spaghetti carbonara, mea...",spaghetti bolognese,spaghetti bolognese,spaghetti bolognese,spaghetti bolognese,spaghetti bolognese,spaghetti bolognese,[spaghetti bolognese which has plate of spaghe...,"[spaghetti bolognese which has garlic, spaghet...",spaghetti bolognese,spaghetti bolognese

In [9]:
df = df_all[["id","image","Attributes_ViT_L_14_descriptors_text_davinci_003_full"]]

In [10]:
df

,id,image,Attributes_ViT_L_14_descriptors_text_davinci_003_full
0,0,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,"[beignet which has square or round in shape, b..."
1,1,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,"[beignets which has served warm, beignets whic..."
2,2,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,"[beignets which has round or square shape, bei..."
3,3,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,[fritter which may be served with a dipping sa...
4,4,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,"[beignet which has square or round in shape, b..."
...,...,...,...
75745,75745,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,[spaghetti bolognese which has plate of spaghe...
75746,75746,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,"[spaghetti bolognese which has ground beef, sp..."
75747,75747,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,[spaghetti bolognese which has plate of spaghe...
75748,75748,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,[spaghetti bolognese which has plate of spaghe...
75749,75749,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,[spaghetti bolognese which has plate of spaghe...

In [11]:
df = df.explode("Attributes_ViT_L_14_descriptors_text_davinci_003_full")

In [12]:
df

,id,image,Attributes_ViT_L_14_descriptors_text_davinci_003_full
0,0,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,beignet which has square or round in shape
0,0,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,beignets which has round or square shape
0,0,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,beignets which has served warm
0,0,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,"pancake which has fork, knife, or other utensils"
0,0,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,beignets which has deep-fried dough
...,...,...,...
75749,75749,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,spaghetti bolognese which has plate of spaghetti
75749,75749,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,spaghetti bolognese which has tomatoes
75749,75749,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,spaghetti bolognese which has herbs
75749,75749,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,spaghetti bolognese which is a spoon or fork
75749,75749,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,spaghetti bolognese which has onions

In [13]:
df = df.rename(columns={
    "id":"image_id",
    "Attributes_ViT_L_14_descriptors_text_davinci_003_full":"caption"
})

In [14]:
df

,image_id,image,caption
0,0,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,beignet which has square or round in shape
0,0,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,beignets which has round or square shape
0,0,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,beignets which has served warm
0,0,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,"pancake which has fork, knife, or other utensils"
0,0,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,beignets which has deep-fried dough
...,...,...,...
75749,75749,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,spaghetti bolognese which has plate of spaghetti
75749,75749,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,spaghetti bolognese which has tomatoes
75749,75749,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,spaghetti bolognese which has herbs
75749,75749,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,spaghetti bolognese which is a spoon or fork
75749,75749,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,spaghetti bolognese which has onions

In [15]:
images_df = df[["image_id","image"]].drop_duplicates("image_id")

In [16]:
images_df

       image_id                                              image
0             0  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...
1             1  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...
2             2  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...
3             3  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...
4             4  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...
...         ...                                                ...
75745     75745  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...
75746     75746  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...
75747     75747  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...
75748     75748  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...
75749     75749  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...

[75750 rows x 2 columns]

In [17]:
captions_df = df[["image_id","caption"]]

In [18]:
captions_df

       image_id                                           caption
0             0        beignet which has square or round in shape
0             0          beignets which has round or square shape
0             0                    beignets which has served warm
0             0  pancake which has fork, knife, or other utensils
0             0               beignets which has deep-fried dough
...         ...                                               ...
75749     75749  spaghetti bolognese which has plate of spaghetti
75749     75749            spaghetti bolognese which has tomatoes
75749     75749               spaghetti bolognese which has herbs
75749     75749      spaghetti bolognese which is a spoon or fork
75749     75749              spaghetti bolognese which has onions

[378478 rows x 2 columns]

In [19]:
images_df.to_parquet("images.parquet")

In [20]:
captions_df.to_parquet("captions.parquet")

In [ ]:
df_all = df_all[["image", "Attributes_ViT_L_14_descriptors_text_davinci_003_full"]]

In [ ]:
df_all

In [ ]:
df_all = df_all.explode("Attributes_ViT_L_14_descriptors_text_davinci_003_full").reset_index(drop=True)

In [ ]:
df_all

In [ ]:
print(df_all.head())
print("Total training pairs:", len(df_all))

In [ ]:
df_all = df_all.dropna(subset=["Attributes_ViT_L_14_descriptors_text_davinci_003_full"])

In [ ]:
df_all.shape

In [ ]:
df_all["Attributes_ViT_L_14_descriptors_text_davinci_003_full"] = df_all["Attributes_ViT_L_14_descriptors_text_davinci_003_full"].astype(str)

In [ ]:
df_all

In [ ]:
df_all.to_parquet("data/food_caption_dataset.parquet")

In [ ]:
import pandas as pd
import glob
import pyarrow as pa
import pyarrow.parquet as pq

files = sorted(glob.glob("data/*.parquet"))

output_file = "data/food_caption_dataset.parquet"

writer = None

for f in files:
    print("Processing:", f)

    df = pd.read_parquet(f)

    df = df[[
        "image",
        "Attributes_ViT_L_14_descriptors_text_davinci_003_full"
    ]]

    df = df.rename(columns={
        "Attributes_ViT_L_14_descriptors_text_davinci_003_full": "caption"
    })

    df = df.explode("caption")
    df = df.dropna(subset=["caption"])

    table = pa.Table.from_pandas(df)

    if writer is None:
        writer = pq.ParquetWriter(output_file, table.schema)

    writer.write_table(table)

if writer:
    writer.close()

print("✅ Parquet dataset saved successfully")

In [ ]:
captions = df_all[["id","captions"]]

captions = captions.rename(columns={
    "id":"image_id",
    "captions":"caption"
})

captions.to_parquet("captions.parquet")

In [ ]:
df_all["image_id"] = df_all.index

In [ ]:
import pyarrow.parquet as pq
import pandas as pd

parquet_file = pq.ParquetFile("data/food_caption_dataset.parquet")

seen_ids = set()
global_idx = 0

for i, batch in enumerate(parquet_file.iter_batches(batch_size=20000)):

    df = batch.to_pandas()

    # image_id generate
    df["image_id"] = range(global_idx, global_idx + len(df))
    global_idx += len(df)

    df = df[["image_id","image"]]

    df = df[~df["image_id"].isin(seen_ids)]

    seen_ids.update(df["image_id"])

    df.to_parquet(f"images_part_{i}.parquet")

In [ ]:
parquet_file = pq.ParquetFile("data/food_caption_dataset.parquet")

In [ ]:
seen_ids = set()

for i, batch in enumerate(parquet_file.iter_batches(batch_size=20000)):

    df = batch.to_pandas()

    df["image_id"] = range(i*20000, i*20000 + len(df))

    # -------- IMAGES --------
    images = df[["image_id","image"]]
    images.to_parquet(f"images_part_{i}.parquet")

    # -------- CAPTIONS --------
    caption_col = [c for c in df.columns if "descriptors_text_davinci" in c][0]

    captions = df[["image_id", caption_col]]

    captions = captions.explode(caption_col)

    captions = captions.rename(columns={caption_col:"caption"})

    captions.to_parquet(f"captions_part_{i}.parquet")

    print(f"Processed batch {i}")

In [ ]:
df_all